# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_CoinbaseAccount__get_accounts <- function(limit, max_pages) {
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1)
  }
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_CoinbaseAccount__get_accounts <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("uuid", "name", "currency", "available_balance", "hold", "active", "default", "ready", "type", "platform", "retail_portfolio_id", "created_at", "updated_at"))
  assert_character(value[["uuid"]])
  assert_character(value[["name"]])
  assert_character(value[["currency"]])
  assert_double(value[["available_balance"]])
  assert_double(value[["hold"]])
  assert_logical(value[["active"]])
  assert_logical(value[["default"]])
  assert_logical(value[["ready"]])
  assert_character(value[["type"]])
  assert_character(value[["platform"]])
  assert_character(value[["retail_portfolio_id"]])
  assert_datetime(value[["created_at"]])
  assert_datetime(value[["updated_at"]])
  return(value)
}

assert_args_CoinbaseAccount__get_account <- function(account_uuid) {
  assert_scalar_character(account_uuid)
  return(invisible(NULL))
}

assert_return_CoinbaseAccount__get_account <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("uuid", "name", "currency", "available_balance", "hold", "active", "default", "ready", "type", "platform", "retail_portfolio_id", "created_at", "updated_at"))
  assert_character(value[["uuid"]])
  assert_character(value[["name"]])
  assert_character(value[["currency"]])
  assert_double(value[["available_balance"]])
  assert_double(value[["hold"]])
  assert_logical(value[["active"]])
  assert_logical(value[["default"]])
  assert_logical(value[["ready"]])
  assert_character(value[["type"]])
  assert_character(value[["platform"]])
  assert_character(value[["retail_portfolio_id"]])
  assert_datetime(value[["created_at"]])
  assert_datetime(value[["updated_at"]])
  return(value)
}

assert_args_CoinbaseAccount__get_fees <- function(product_type) {
  if (!is.null(product_type)) {
    assert_scalar_character(product_type)
  }
  return(invisible(NULL))
}

assert_return_CoinbaseAccount__get_fees <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("pricing_tier", "maker_fee_rate", "taker_fee_rate", "usd_from", "usd_to", "total_volume", "total_fees", "total_balance"))
  assert_character(value[["pricing_tier"]])
  assert_double(value[["maker_fee_rate"]])
  assert_double(value[["taker_fee_rate"]])
  assert_double(value[["usd_from"]])
  assert_double(value[["usd_to"]])
  assert_double(value[["total_volume"]])
  assert_double(value[["total_fees"]])
  assert_double(value[["total_balance"]])
  return(value)
}

assert_return_CoinbaseAccount__get_portfolios <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("uuid", "name", "type", "deleted"))
  assert_character(value[["uuid"]])
  assert_no_missing_values(value[["uuid"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["type"]])
  assert_no_missing_values(value[["type"]])
  assert_logical(value[["deleted"]])
  assert_no_missing_values(value[["deleted"]])
  return(value)
}

assert_args_CoinbaseAccount__get_portfolio_breakdown <- function(portfolio_uuid, currency) {
  assert_scalar_character(portfolio_uuid)
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_CoinbaseAccount__get_portfolio_breakdown <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_CoinbaseAccount__get_portfolio_summary <- function(portfolio_uuid, currency) {
  assert_scalar_character(portfolio_uuid)
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_CoinbaseAccount__get_portfolio_summary <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("uuid", "name", "type", "total_balance", "total_futures_balance", "total_cash_equivalent_balance", "total_crypto_balance", "futures_unrealized_pnl", "perp_unrealized_pnl", "total_equities_balance"))
  assert_character(value[["uuid"]])
  assert_character(value[["name"]])
  assert_character(value[["type"]])
  assert_double(value[["total_balance"]])
  assert_double(value[["total_futures_balance"]])
  assert_double(value[["total_cash_equivalent_balance"]])
  assert_double(value[["total_crypto_balance"]])
  assert_double(value[["futures_unrealized_pnl"]])
  assert_double(value[["perp_unrealized_pnl"]])
  assert_double(value[["total_equities_balance"]])
  return(value)
}

assert_return_CoinbaseAccount__get_key_permissions <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("can_view", "can_trade", "can_transfer", "portfolio_uuid", "portfolio_type"))
  assert_logical(value[["can_view"]])
  assert_no_missing_values(value[["can_view"]])
  assert_logical(value[["can_trade"]])
  assert_no_missing_values(value[["can_trade"]])
  assert_logical(value[["can_transfer"]])
  assert_no_missing_values(value[["can_transfer"]])
  assert_character(value[["portfolio_uuid"]])
  assert_no_missing_values(value[["portfolio_uuid"]])
  assert_character(value[["portfolio_type"]])
  assert_no_missing_values(value[["portfolio_type"]])
  return(value)
}

assert_args_CoinbaseBase__initialize <- function(keys, base_url, exchange_base_url, async) {
  if (!is.null(keys)) {
    assert_list(keys)
  }
  assert_scalar_character(base_url)
  assert_scalar_character(exchange_base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_CoinbaseBase__initialize <- function(value) {
  assert_class(value, "CoinbaseBase")
  return(value)
}

assert_return_CoinbaseFutures__get_balance_summary <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("futures_buying_power", "total_usd_balance", "cbi_usd_balance", "cfm_usd_balance", "total_open_orders_hold_amount", "unrealized_pnl", "daily_realized_pnl", "initial_margin", "available_margin", "liquidation_threshold", "liquidation_buffer_amount", "liquidation_buffer_percentage"))
  assert_double(value[["futures_buying_power"]])
  assert_double(value[["total_usd_balance"]])
  assert_double(value[["cbi_usd_balance"]])
  assert_double(value[["cfm_usd_balance"]])
  assert_double(value[["total_open_orders_hold_amount"]])
  assert_double(value[["unrealized_pnl"]])
  assert_double(value[["daily_realized_pnl"]])
  assert_double(value[["initial_margin"]])
  assert_double(value[["available_margin"]])
  assert_double(value[["liquidation_threshold"]])
  assert_double(value[["liquidation_buffer_amount"]])
  assert_double(value[["liquidation_buffer_percentage"]])
  return(value)
}

assert_return_CoinbaseFutures__get_positions <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("product_id", "side", "number_of_contracts", "current_price", "avg_entry_price", "unrealized_pnl", "daily_realized_pnl", "expiration_time"))
  assert_character(value[["product_id"]])
  assert_character(value[["side"]])
  assert_double(value[["number_of_contracts"]])
  assert_double(value[["current_price"]])
  assert_double(value[["avg_entry_price"]])
  assert_double(value[["unrealized_pnl"]])
  assert_double(value[["daily_realized_pnl"]])
  assert_datetime(value[["expiration_time"]])
  return(value)
}

assert_return_CoinbaseFutures__get_position <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("product_id", "side", "number_of_contracts", "current_price", "avg_entry_price", "unrealized_pnl", "daily_realized_pnl", "expiration_time"))
  assert_character(value[["product_id"]])
  assert_character(value[["side"]])
  assert_double(value[["number_of_contracts"]])
  assert_double(value[["current_price"]])
  assert_double(value[["avg_entry_price"]])
  assert_double(value[["unrealized_pnl"]])
  assert_double(value[["daily_realized_pnl"]])
  assert_datetime(value[["expiration_time"]])
  return(value)
}

assert_return_CoinbaseFutures__schedule_sweep <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("success"))
  assert_logical(value[["success"]])
  assert_no_missing_values(value[["success"]])
  return(value)
}

assert_return_CoinbaseFutures__get_sweeps <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "requested_amount", "should_sweep_all", "status", "schedule_time"))
  assert_character(value[["id"]])
  assert_double(value[["requested_amount"]])
  assert_logical(value[["should_sweep_all"]])
  assert_character(value[["status"]])
  assert_datetime(value[["schedule_time"]])
  return(value)
}

assert_return_CoinbaseFutures__cancel_sweep <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("success"))
  assert_logical(value[["success"]])
  assert_no_missing_values(value[["success"]])
  return(value)
}

assert_return_CoinbaseFutures__get_intraday_margin_setting <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("setting"))
  assert_character(value[["setting"]])
  assert_no_missing_values(value[["setting"]])
  return(value)
}

assert_args_CoinbaseFutures__set_intraday_margin_setting <- function(setting) {
  assert_scalar_character(setting)
  return(invisible(NULL))
}

assert_return_CoinbaseFutures__set_intraday_margin_setting <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("setting"))
  assert_character(value[["setting"]])
  assert_no_missing_values(value[["setting"]])
  return(value)
}

assert_args_CoinbaseFutures__get_current_margin_window <- function(margin_profile_type) {
  assert_scalar_character(margin_profile_type)
  return(invisible(NULL))
}

assert_return_CoinbaseFutures__get_current_margin_window <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("margin_window_type", "end_time", "is_intraday_margin_killswitch_enabled", "is_intraday_margin_enrollment_killswitch_enabled"))
  assert_character(value[["margin_window_type"]])
  assert_datetime(value[["end_time"]])
  assert_logical(value[["is_intraday_margin_killswitch_enabled"]])
  assert_logical(value[["is_intraday_margin_enrollment_killswitch_enabled"]])
  return(value)
}

assert_return_CoinbaseMarketData__get_products <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "base_currency", "quote_currency", "quote_increment", "base_increment", "display_name", "min_market_funds", "margin_enabled", "post_only", "limit_only", "cancel_only", "status", "status_message", "trading_disabled", "fx_stablecoin", "max_slippage_percentage", "auction_mode", "high_bid_limit_percentage"))
  assert_character(value[["id"]])
  assert_character(value[["base_currency"]])
  assert_character(value[["quote_currency"]])
  assert_character(value[["quote_increment"]])
  assert_character(value[["base_increment"]])
  assert_character(value[["display_name"]])
  assert_character(value[["min_market_funds"]])
  assert_logical(value[["margin_enabled"]])
  assert_logical(value[["post_only"]])
  assert_logical(value[["limit_only"]])
  assert_logical(value[["cancel_only"]])
  assert_character(value[["status"]])
  assert_character(value[["status_message"]])
  assert_logical(value[["trading_disabled"]])
  assert_logical(value[["fx_stablecoin"]])
  assert_character(value[["max_slippage_percentage"]])
  assert_logical(value[["auction_mode"]])
  assert_character(value[["high_bid_limit_percentage"]])
  return(value)
}

assert_return_CoinbaseMarketData__get_product <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "base_currency", "quote_currency", "quote_increment", "base_increment", "display_name", "min_market_funds", "margin_enabled", "post_only", "limit_only", "cancel_only", "status", "status_message", "trading_disabled", "fx_stablecoin", "max_slippage_percentage", "auction_mode", "high_bid_limit_percentage"))
  assert_character(value[["id"]])
  assert_character(value[["base_currency"]])
  assert_character(value[["quote_currency"]])
  assert_character(value[["quote_increment"]])
  assert_character(value[["base_increment"]])
  assert_character(value[["display_name"]])
  assert_character(value[["min_market_funds"]])
  assert_logical(value[["margin_enabled"]])
  assert_logical(value[["post_only"]])
  assert_logical(value[["limit_only"]])
  assert_logical(value[["cancel_only"]])
  assert_character(value[["status"]])
  assert_character(value[["status_message"]])
  assert_logical(value[["trading_disabled"]])
  assert_logical(value[["fx_stablecoin"]])
  assert_character(value[["max_slippage_percentage"]])
  assert_logical(value[["auction_mode"]])
  assert_character(value[["high_bid_limit_percentage"]])
  return(value)
}

assert_args_CoinbaseMarketData__get_ohlcv <- function(start, end) {
  if (!is.null(start)) {
    assert_datetime(start)
    assert_no_missing_values(start)
  }
  if (!is.null(end)) {
    assert_datetime(end)
    assert_no_missing_values(end)
  }
  return(invisible(NULL))
}

assert_return_CoinbaseMarketData__get_ohlcv <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("datetime", "open", "high", "low", "close", "volume"))
  assert_datetime(value[["datetime"]])
  assert_double(value[["open"]])
  assert_double(value[["high"]])
  assert_double(value[["low"]])
  assert_double(value[["close"]])
  assert_double(value[["volume"]])
  return(value)
}

assert_args_CoinbaseMarketData__get_trades <- function(limit, after) {
  assert_scalar_count(limit)
  assert_between(limit, lower = 1)
  if (!is.null(after)) {
    assert_scalar_double(after)
  }
  return(invisible(NULL))
}

assert_return_CoinbaseMarketData__get_trades <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("trade_id", "side", "price", "size", "time"))
  assert_double(value[["trade_id"]])
  assert_character(value[["side"]])
  assert_double(value[["price"]])
  assert_double(value[["size"]])
  assert_datetime(value[["time"]])
  return(value)
}

assert_args_CoinbaseMarketData__get_trades_history <- function(start, end, max_pages) {
  if (!is.null(start)) {
    assert_datetime(start)
    assert_no_missing_values(start)
  }
  if (!is.null(end)) {
    assert_datetime(end)
    assert_no_missing_values(end)
  }
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_CoinbaseMarketData__get_trades_history <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("trade_id", "side", "price", "size", "time"))
  assert_double(value[["trade_id"]])
  assert_character(value[["side"]])
  assert_double(value[["price"]])
  assert_double(value[["size"]])
  assert_datetime(value[["time"]])
  return(value)
}

assert_args_CoinbaseMarketData__get_orderbook <- function(level) {
  assert_scalar_count(level)
  assert_between(level, lower = 1, upper = 3)
  return(invisible(NULL))
}

assert_return_CoinbaseMarketData__get_orderbook <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_CoinbaseMarketData__get_ticker <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("price", "size", "time", "bid", "ask", "volume"))
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["size"]])
  assert_no_missing_values(value[["size"]])
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_double(value[["bid"]])
  assert_no_missing_values(value[["bid"]])
  assert_double(value[["ask"]])
  assert_no_missing_values(value[["ask"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  return(value)
}

assert_return_CoinbaseMarketData__get_stats <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("product_id", "open", "high", "low", "last", "volume", "volume_30day"))
  assert_character(value[["product_id"]])
  assert_double(value[["open"]])
  assert_double(value[["high"]])
  assert_double(value[["low"]])
  assert_double(value[["last"]])
  assert_double(value[["volume"]])
  assert_double(value[["volume_30day"]])
  return(value)
}

assert_return_CoinbaseMarketData__get_product_stats <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("open", "high", "low", "last", "volume", "volume_30day", "rfq_volume_24hour", "rfq_volume_30day", "conversions_volume_24hour", "conversions_volume_30day"))
  assert_double(value[["open"]])
  assert_double(value[["high"]])
  assert_double(value[["low"]])
  assert_double(value[["last"]])
  assert_double(value[["volume"]])
  assert_double(value[["volume_30day"]])
  assert_double(value[["rfq_volume_24hour"]])
  assert_double(value[["rfq_volume_30day"]])
  assert_double(value[["conversions_volume_24hour"]])
  assert_double(value[["conversions_volume_30day"]])
  return(value)
}

assert_args_CoinbaseMarketData__get_best_bid_ask <- function(product_ids) {
  if (!is.null(product_ids)) {
    assert_character(product_ids)
    assert_no_missing_values(product_ids)
  }
  return(invisible(NULL))
}

assert_return_CoinbaseMarketData__get_best_bid_ask <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("product_id", "bid_price", "bid_size", "ask_price", "ask_size", "time"))
  assert_character(value[["product_id"]])
  assert_double(value[["bid_price"]])
  assert_double(value[["bid_size"]])
  assert_double(value[["ask_price"]])
  assert_double(value[["ask_size"]])
  assert_datetime(value[["time"]])
  return(value)
}

assert_return_CoinbaseMarketData__get_server_time <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("iso", "epoch"))
  assert_character(value[["iso"]])
  assert_no_missing_values(value[["iso"]])
  assert_double(value[["epoch"]])
  assert_no_missing_values(value[["epoch"]])
  return(value)
}

assert_args_CoinbaseTrading__add_order <- function(client_order_id, self_trade_prevention_id, leverage, margin_type, retail_portfolio_id) {
  assert_scalar_character(client_order_id)
  if (!is.null(self_trade_prevention_id)) {
    assert_scalar_character(self_trade_prevention_id)
  }
  if (!is.null(leverage)) {
    assert_scalar_character(leverage)
  }
  if (!is.null(margin_type)) {
    assert_scalar_character(margin_type)
  }
  if (!is.null(retail_portfolio_id)) {
    assert_scalar_character(retail_portfolio_id)
  }
  return(invisible(NULL))
}

assert_return_CoinbaseTrading__add_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("success", "order_id", "product_id", "side", "client_order_id", "failure_reason", "config_type", "base_size", "quote_size", "limit_price", "stop_price", "stop_trigger_price"))
  assert_logical(value[["success"]])
  assert_character(value[["order_id"]])
  assert_character(value[["product_id"]])
  assert_character(value[["side"]])
  assert_character(value[["client_order_id"]])
  assert_character(value[["failure_reason"]])
  assert_character(value[["config_type"]])
  assert_double(value[["base_size"]])
  assert_double(value[["quote_size"]])
  assert_double(value[["limit_price"]])
  assert_double(value[["stop_price"]])
  assert_double(value[["stop_trigger_price"]])
  return(value)
}

assert_args_CoinbaseTrading__preview_order <- function(leverage, margin_type, retail_portfolio_id) {
  if (!is.null(leverage)) {
    assert_scalar_character(leverage)
  }
  if (!is.null(margin_type)) {
    assert_scalar_character(margin_type)
  }
  if (!is.null(retail_portfolio_id)) {
    assert_scalar_character(retail_portfolio_id)
  }
  return(invisible(NULL))
}

assert_return_CoinbaseTrading__preview_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("order_total", "commission_total", "quote_size", "base_size", "best_bid", "best_ask", "slippage", "errs", "preview_id"))
  assert_double(value[["order_total"]])
  assert_double(value[["commission_total"]])
  assert_double(value[["quote_size"]])
  assert_double(value[["base_size"]])
  assert_double(value[["best_bid"]])
  assert_double(value[["best_ask"]])
  assert_double(value[["slippage"]])
  assert_character(value[["errs"]])
  assert_character(value[["preview_id"]])
  return(value)
}

assert_args_CoinbaseTrading__get_order <- function(order_id) {
  assert_scalar_character(order_id)
  return(invisible(NULL))
}

assert_return_CoinbaseTrading__get_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("order_id", "client_order_id", "product_id", "side", "status", "order_type", "config_type", "time_in_force", "created_time", "completion_percentage", "filled_size", "average_filled_price", "number_of_fills", "filled_value", "total_fees", "base_size", "quote_size", "limit_price", "stop_price", "stop_trigger_price", "stop_direction", "end_time", "post_only"))
  assert_character(value[["order_id"]])
  assert_character(value[["client_order_id"]])
  assert_character(value[["product_id"]])
  assert_character(value[["side"]])
  assert_character(value[["status"]])
  assert_character(value[["order_type"]])
  assert_character(value[["config_type"]])
  assert_character(value[["time_in_force"]])
  assert_datetime(value[["created_time"]])
  assert_double(value[["completion_percentage"]])
  assert_double(value[["filled_size"]])
  assert_double(value[["average_filled_price"]])
  assert_double(value[["number_of_fills"]])
  assert_double(value[["filled_value"]])
  assert_double(value[["total_fees"]])
  assert_double(value[["base_size"]])
  assert_double(value[["quote_size"]])
  assert_double(value[["limit_price"]])
  assert_double(value[["stop_price"]])
  assert_double(value[["stop_trigger_price"]])
  assert_character(value[["stop_direction"]])
  assert_datetime(value[["end_time"]])
  assert_logical(value[["post_only"]])
  return(value)
}

assert_args_CoinbaseTrading__get_orders <- function(product_ids, order_status, order_side, limit, order_ids, start_date, end_date, order_types, product_type, order_placement_source, contract_expiry_type, asset_filters, retail_portfolio_id, time_in_forces, sort_by, max_pages) {
  if (!is.null(product_ids)) {
    assert_character(product_ids)
    assert_no_missing_values(product_ids)
  }
  if (!is.null(order_status)) {
    assert_character(order_status)
    assert_no_missing_values(order_status)
  }
  if (!is.null(order_side)) {
    assert_scalar_character(order_side)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1)
  }
  if (!is.null(order_ids)) {
    assert_character(order_ids)
    assert_no_missing_values(order_ids)
  }
  if (!is.null(start_date)) {
    assert_scalar_character(start_date)
  }
  if (!is.null(end_date)) {
    assert_scalar_character(end_date)
  }
  if (!is.null(order_types)) {
    assert_character(order_types)
    assert_no_missing_values(order_types)
  }
  if (!is.null(product_type)) {
    assert_scalar_character(product_type)
  }
  if (!is.null(order_placement_source)) {
    assert_scalar_character(order_placement_source)
  }
  if (!is.null(contract_expiry_type)) {
    assert_scalar_character(contract_expiry_type)
  }
  if (!is.null(asset_filters)) {
    assert_character(asset_filters)
    assert_no_missing_values(asset_filters)
  }
  if (!is.null(retail_portfolio_id)) {
    assert_scalar_character(retail_portfolio_id)
  }
  if (!is.null(time_in_forces)) {
    assert_character(time_in_forces)
    assert_no_missing_values(time_in_forces)
  }
  if (!is.null(sort_by)) {
    assert_scalar_character(sort_by)
  }
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_CoinbaseTrading__get_orders <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("order_id", "client_order_id", "product_id", "side", "status", "order_type", "config_type", "time_in_force", "created_time", "completion_percentage", "filled_size", "average_filled_price", "number_of_fills", "filled_value", "total_fees", "base_size", "quote_size", "limit_price", "stop_price", "stop_trigger_price", "stop_direction", "end_time", "post_only"))
  assert_character(value[["order_id"]])
  assert_character(value[["client_order_id"]])
  assert_character(value[["product_id"]])
  assert_character(value[["side"]])
  assert_character(value[["status"]])
  assert_character(value[["order_type"]])
  assert_character(value[["config_type"]])
  assert_character(value[["time_in_force"]])
  assert_datetime(value[["created_time"]])
  assert_double(value[["completion_percentage"]])
  assert_double(value[["filled_size"]])
  assert_double(value[["average_filled_price"]])
  assert_double(value[["number_of_fills"]])
  assert_double(value[["filled_value"]])
  assert_double(value[["total_fees"]])
  assert_double(value[["base_size"]])
  assert_double(value[["quote_size"]])
  assert_double(value[["limit_price"]])
  assert_double(value[["stop_price"]])
  assert_double(value[["stop_trigger_price"]])
  assert_character(value[["stop_direction"]])
  assert_datetime(value[["end_time"]])
  assert_logical(value[["post_only"]])
  return(value)
}

assert_args_CoinbaseTrading__get_fills <- function(order_ids, trade_ids, product_ids, start_sequence_timestamp, end_sequence_timestamp, retail_portfolio_id, limit, sort_by, max_pages) {
  if (!is.null(order_ids)) {
    assert_character(order_ids)
    assert_no_missing_values(order_ids)
  }
  if (!is.null(trade_ids)) {
    assert_character(trade_ids)
    assert_no_missing_values(trade_ids)
  }
  if (!is.null(product_ids)) {
    assert_character(product_ids)
    assert_no_missing_values(product_ids)
  }
  if (!is.null(start_sequence_timestamp)) {
    assert_scalar_character(start_sequence_timestamp)
  }
  if (!is.null(end_sequence_timestamp)) {
    assert_scalar_character(end_sequence_timestamp)
  }
  if (!is.null(retail_portfolio_id)) {
    assert_scalar_character(retail_portfolio_id)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1)
  }
  if (!is.null(sort_by)) {
    assert_scalar_character(sort_by)
  }
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_CoinbaseTrading__get_fills <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("entry_id", "trade_id", "order_id", "product_id", "side", "trade_time", "trade_type", "price", "size", "commission", "size_in_quote", "liquidity_indicator"))
  assert_character(value[["entry_id"]])
  assert_character(value[["trade_id"]])
  assert_character(value[["order_id"]])
  assert_character(value[["product_id"]])
  assert_character(value[["side"]])
  assert_datetime(value[["trade_time"]])
  assert_character(value[["trade_type"]])
  assert_double(value[["price"]])
  assert_double(value[["size"]])
  assert_double(value[["commission"]])
  assert_logical(value[["size_in_quote"]])
  assert_character(value[["liquidity_indicator"]])
  return(value)
}

assert_args_CoinbaseTrading__edit_order <- function(order_id) {
  assert_scalar_character(order_id)
  return(invisible(NULL))
}

assert_return_CoinbaseTrading__edit_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("success", "order_id", "errors"))
  assert_logical(value[["success"]])
  assert_character(value[["order_id"]])
  assert_character(value[["errors"]])
  return(value)
}

assert_args_CoinbaseTrading__preview_edit_order <- function(order_id) {
  assert_scalar_character(order_id)
  return(invisible(NULL))
}

assert_return_CoinbaseTrading__preview_edit_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("errors", "slippage", "order_total", "commission_total", "quote_size", "base_size", "best_bid", "average_filled_price"))
  assert_character(value[["errors"]])
  assert_double(value[["slippage"]])
  assert_double(value[["order_total"]])
  assert_double(value[["commission_total"]])
  assert_double(value[["quote_size"]])
  assert_double(value[["base_size"]])
  assert_double(value[["best_bid"]])
  assert_double(value[["average_filled_price"]])
  return(value)
}

assert_args_CoinbaseTrading__cancel_orders <- function(order_ids) {
  assert_character(order_ids)
  assert_no_missing_values(order_ids)
  return(invisible(NULL))
}

assert_return_CoinbaseTrading__cancel_orders <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("order_id", "success", "failure_reason"))
  assert_character(value[["order_id"]])
  assert_logical(value[["success"]])
  assert_character(value[["failure_reason"]])
  return(value)
}

assert_args_CoinbaseTrading__close_position <- function(client_order_id) {
  assert_scalar_character(client_order_id)
  return(invisible(NULL))
}

assert_return_CoinbaseTrading__close_position <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("success", "order_id", "product_id", "side", "client_order_id", "failure_reason", "config_type", "base_size", "quote_size", "limit_price", "stop_price", "stop_trigger_price"))
  assert_logical(value[["success"]])
  assert_character(value[["order_id"]])
  assert_character(value[["product_id"]])
  assert_character(value[["side"]])
  assert_character(value[["client_order_id"]])
  assert_character(value[["failure_reason"]])
  assert_character(value[["config_type"]])
  assert_double(value[["base_size"]])
  assert_double(value[["quote_size"]])
  assert_double(value[["limit_price"]])
  assert_double(value[["stop_price"]])
  assert_double(value[["stop_trigger_price"]])
  return(value)
}

assert_args_coinbase_backfill_trades <- function(symbols, from, to, base_url, exchange_base_url, max_pages, sleep, verbose) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  assert_any_of(
    from,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_any_of(
    to,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_scalar_character(base_url)
  assert_scalar_character(exchange_base_url)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_logical(verbose)
  return(invisible(NULL))
}

assert_return_coinbase_backfill_trades <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_verify_symbol <- function(product_id) {
  assert_scalar_character(product_id)
  return(invisible(NULL))
}

assert_return_verify_symbol <- function(value) {
  assert_scalar_logical(value)
  return(value)
}

assert_args_trades_to_ohlcv <- function(trades, interval) {
  assert_class(trades, "data.table")
  assert_scalar_double(interval)
  assert_between(interval, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_trades_to_ohlcv <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("datetime", "open", "high", "low", "close", "volume"))
  assert_datetime(value[["datetime"]])
  assert_double(value[["open"]])
  assert_double(value[["high"]])
  assert_double(value[["low"]])
  assert_double(value[["close"]])
  assert_double(value[["volume"]])
  return(value)
}

assert_args_coalesce_null <- function(x, default) {
  return(invisible(NULL))
}

assert_return_coalesce_null <- function(value) {
  return(value)
}

assert_args_num_or_na <- function(x) {
  return(invisible(NULL))
}

assert_return_num_or_na <- function(value) {
  assert_double(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_flex_num <- function(x) {
  return(invisible(NULL))
}

assert_return_flex_num <- function(value) {
  assert_double(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_amount_value <- function(x) {
  if (!is.null(x)) {
    assert_list(x)
  }
  return(invisible(NULL))
}

assert_return_amount_value <- function(value) {
  assert_double(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_money_value <- function(x) {
  return(invisible(NULL))
}

assert_return_money_value <- function(value) {
  assert_double(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_nth_num <- function(x, i) {
  if (!is.null(x)) {
    assert_any_of(
      x,
      function(.x) {
        assert_list(.x)
      },
      function(.x) {
        
      }
    )
  }
  assert_scalar_count(i)
  assert_between(i, lower = 1)
  return(invisible(NULL))
}

assert_return_nth_num <- function(value) {
  assert_double(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_nth_chr <- function(x, i) {
  if (!is.null(x)) {
    assert_any_of(
      x,
      function(.x) {
        assert_list(.x)
      },
      function(.x) {
        
      }
    )
  }
  assert_scalar_count(i)
  assert_between(i, lower = 1)
  return(invisible(NULL))
}

assert_return_nth_chr <- function(value) {
  assert_character(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_collapse_errors <- function(errs) {
  if (!is.null(errs)) {
    assert_list(errs)
  }
  return(invisible(NULL))
}

assert_return_collapse_errors <- function(value) {
  assert_character(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_to_snake_case <- function(names) {
  assert_character(names)
  assert_no_missing_values(names)
  return(invisible(NULL))
}

assert_return_to_snake_case <- function(value) {
  assert_character(value)
  assert_no_missing_values(value)
  return(value)
}

assert_args_as_dt_row <- function(x) {
  if (!is.null(x)) {
    assert_list(x)
  }
  return(invisible(NULL))
}

assert_return_as_dt_row <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_as_dt_list <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_as_dt_list <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_products <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_products <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_candles <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_candles <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_trades <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_trades <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_accounts <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_accounts <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_fees <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_fees <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_flatten_order_config <- function(cfg) {
  if (!is.null(cfg)) {
    assert_list(cfg)
  }
  return(invisible(NULL))
}

assert_return_flatten_order_config <- function(value) {
  assert_list(value)
  assert_has_names(value, c("config_type", "base_size", "quote_size", "limit_price", "stop_price", "stop_trigger_price", "stop_direction", "end_time", "post_only"))
  assert_character(value[["config_type"]])
  assert_length(value[["config_type"]], 1L)
  assert_double(value[["base_size"]])
  assert_length(value[["base_size"]], 1L)
  assert_double(value[["quote_size"]])
  assert_length(value[["quote_size"]], 1L)
  assert_double(value[["limit_price"]])
  assert_length(value[["limit_price"]], 1L)
  assert_double(value[["stop_price"]])
  assert_length(value[["stop_price"]], 1L)
  assert_double(value[["stop_trigger_price"]])
  assert_length(value[["stop_trigger_price"]], 1L)
  assert_character(value[["stop_direction"]])
  assert_length(value[["stop_direction"]], 1L)
  assert_datetime(value[["end_time"]])
  assert_length(value[["end_time"]], 1L)
  assert_logical(value[["post_only"]])
  assert_length(value[["post_only"]], 1L)
  return(value)
}

assert_args_parse_orders <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_orders <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_fills <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_fills <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_preview <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_preview <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_create_order <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_create_order <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_edit_order <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_edit_order <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_edit_preview <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_edit_preview <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_cancel_results <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_cancel_results <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_margin_window <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_margin_window <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_futures_balance <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_futures_balance <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_futures_positions <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_futures_positions <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_futures_sweeps <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_futures_sweeps <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_orderbook <- function(data, level) {
  if (!is.null(data)) {
    assert_list(data)
  }
  assert_scalar_count(level)
  assert_between(level, lower = 1, upper = 3)
  return(invisible(NULL))
}

assert_return_parse_orderbook <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_stats <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_stats <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_product_stats <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_product_stats <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_best_bid_ask <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_best_bid_ask <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_portfolio_breakdown <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_portfolio_breakdown <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_portfolio_summary <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_portfolio_summary <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_load_private_key <- function(private_key) {
  assert_scalar_character(private_key)
  return(invisible(NULL))
}

assert_return_load_private_key <- function(value) {
  assert_class(value, "key")
  return(value)
}

assert_args_build_jwt <- function(keys, method, host, path) {
  assert_list(keys)
  assert_scalar_character(method)
  assert_scalar_character(host)
  assert_scalar_character(path)
  return(invisible(NULL))
}

assert_return_build_jwt <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_coinbase_jwt_sign <- function(req, keys) {
  assert_class(req, "httr2_request")
  assert_list(keys)
  return(invisible(NULL))
}

assert_return_coinbase_jwt_sign <- function(value) {
  assert_class(value, "httr2_request")
  return(value)
}

assert_args_parse_coinbase_response <- function(resp) {
  assert_class(resp, "httr2_response")
  return(invisible(NULL))
}

assert_return_parse_coinbase_response <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_validate_symbol <- function(product_id) {
  assert_scalar_character(product_id)
  return(invisible(NULL))
}

assert_return_validate_symbol <- function(value) {
  assert_scalar_logical(value)
  return(value)
}

assert_args_validate_side <- function(side) {
  assert_scalar_character(side)
  return(invisible(NULL))
}

assert_return_validate_side <- function(value) {
  assert_scalar_character(value)
  assert_value_in_set(value, c("BUY", "SELL"))
  return(value)
}

assert_args_format_decimal <- function(v) {
  assert_scalar_double(v)
  assert_between(v, lower = -Inf, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_format_decimal <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_coerce_positive_string <- function(name) {
  assert_scalar_character(name)
  return(invisible(NULL))
}

assert_return_coerce_positive_string <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_return_validate_order_config <- function(value) {
  assert_scalar_logical(value)
  return(value)
}

assert_args_stringify_order_config <- function(order_configuration) {
  assert_list(order_configuration)
  return(invisible(NULL))
}

assert_return_stringify_order_config <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_get_base_url <- function(url) {
  assert_scalar_character(url)
  return(invisible(NULL))
}

assert_return_get_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_exchange_base_url <- function(url) {
  assert_scalar_character(url)
  return(invisible(NULL))
}

assert_return_get_exchange_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_return_generate_client_order_id <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_api_keys <- function(api_key_name, api_private_key) {
  assert_scalar_character(api_key_name)
  assert_scalar_character(api_private_key)
  return(invisible(NULL))
}

assert_return_get_api_keys <- function(value) {
  assert_list(value)
  assert_has_names(value, c("api_key_name", "api_private_key"))
  assert_scalar_character(value[["api_key_name"]])
  assert_scalar_character(value[["api_private_key"]])
  return(value)
}

assert_args_iso_to_datetime <- function(x) {
  assert_character(x)
  return(invisible(NULL))
}

assert_return_iso_to_datetime <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_s_to_datetime <- function(s) {
  assert_double(s)
  return(invisible(NULL))
}

assert_return_s_to_datetime <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_datetime_to_epoch <- function(x) {
  if (!is.null(x)) {
    assert_any_of(
      x,
      function(.x) {
        assert_datetime(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_date(.x)
        assert_no_missing_values(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_datetime_to_epoch <- function(value) {
  if (!is.null(value)) {
    assert_double(value)
    assert_no_missing_values(value)
  }
  return(value)
}

assert_args_time_convert_from_coinbase <- function(time_value, unit) {
  assert_any_of(
    time_value,
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_scalar_character(unit)
  assert_value_in_set(unit, c("iso", "s"))
  return(invisible(NULL))
}

assert_return_time_convert_from_coinbase <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_time_convert_to_coinbase <- function(datetime, unit) {
  assert_datetime(datetime)
  assert_no_missing_values(datetime)
  assert_scalar_character(unit)
  assert_value_in_set(unit, c("iso", "s"))
  return(invisible(NULL))
}

assert_return_time_convert_to_coinbase <- function(value) {
  assert_any_of(
    value,
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  return(value)
}

